fieldLayouts:
  8576d89f-bd0d-4961-8138-592e07858587:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1c825de5-0eff-466f-a5fe-4ed27a1a71c0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 74276596-14a6-44fe-bde8-a89fb9d91d18 # text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee89ba25-c4fb-4da6-adf0-da961ebd84df
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 792f7eab-1e80-4196-8822-7cadfe94c611
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 2ecd2b44-1ed0-4849-ba7e-02010375e469 # footer
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
