defaultPlacement: end
enableVersioning: true
handle: artist
name: artist
propagationMethod: all
siteSettings:
  4dda5e9c-e6e0-41fc-a1ac-201ccb37d216: # Weshmusic
    enabledByDefault: true
    hasUrls: true
    template: artist/_entry
    uriFormat: 'artist/{slug}'
type: channel
