defaultPlacement: end
enableVersioning: true
handle: footer
name: footer
propagationMethod: all
siteSettings:
  4dda5e9c-e6e0-41fc-a1ac-201ccb37d216: # Weshmusic
    enabledByDefault: true
    hasUrls: true
    template: footer/_entry
    uriFormat: 'footer/{slug}'
type: channel
