defaultPlacement: end
enableVersioning: true
handle: song
name: song
propagationMethod: all
siteSettings:
  4dda5e9c-e6e0-41fc-a1ac-201ccb37d216: # Weshmusic
    enabledByDefault: true
    hasUrls: true
    template: song/_entry
    uriFormat: 'song/{slug}'
type: channel
